import { Chore, TeamMember } from './types'

export const sampleTeamMembers: TeamMember[] = [
  { id: 'tm1', name: 'Alice', color: '#F44336' },
  { id: 'tm2', name: 'Bob', color: '#2196F3' },
  { id: 'tm3', name: 'Carol', color: '#4CAF50' },
  { id: 'tm4', name: 'Dave', color: '#FF9800' },
  { id: 'tm5', name: 'Edward', color: '#9C27B0' },
]

export const sampleChores: Chore[] = [
  {
    id: 'c1',
    title: 'Clean kitchen',
    description: 'Wipe counters, clean sink, mop floor',
    assigneeId: 'tm1',
    category: 'cleaning',
    priority: 'high',
    dueDate: '2024-12-27',
    recurrence: { type: 'weekly', interval: 1, daysOfWeek: [1, 5], endDate: null },
    completedDates: ['2024-12-23'],
    createdAt: '2024-12-01T00:00:00.000Z',
  },
  {
    id: 'c2',
    title: 'Empty trash bins',
    description: 'All office trash and recycling',
    assigneeId: 'tm2',
    category: 'cleaning',
    priority: 'medium',
    dueDate: '2024-12-27',
    recurrence: { type: 'daily', interval: 1, daysOfWeek: [], endDate: null },
    completedDates: ['2024-12-25', '2024-12-26'],
    createdAt: '2024-12-01T00:00:00.000Z',
  },
  {
    id: 'c3',
    title: 'Water office plants',
    description: 'Check soil moisture first',
    assigneeId: 'tm3',
    category: 'maintenance',
    priority: 'low',
    dueDate: '2024-12-25',
    recurrence: { type: 'weekly', interval: 1, daysOfWeek: [1, 4], endDate: null },
    completedDates: [],
    createdAt: '2024-12-01T00:00:00.000Z',
  },
  {
    id: 'c4',
    title: 'Restock supplies',
    description: 'Paper towels, soap, coffee, snacks',
    assigneeId: 'tm4',
    category: 'admin',
    priority: 'medium',
    dueDate: '2024-12-30',
    recurrence: { type: 'none', interval: 1, daysOfWeek: [], endDate: null },
    completedDates: [],
    createdAt: '2024-12-01T00:00:00.000Z',
  },
  {
    id: 'c5',
    title: 'HVAC filter check',
    description: 'Replace if dirty',
    assigneeId: 'tm1',
    category: 'maintenance',
    priority: 'high',
    dueDate: '2025-01-02',
    recurrence: { type: 'none', interval: 1, daysOfWeek: [], endDate: null },
    completedDates: [],
    createdAt: '2024-12-01T00:00:00.000Z',
  },
  {
    id: 'c6',
    title: 'Vacuum conference room',
    description: 'Including under the table',
    assigneeId: 'tm2',
    category: 'cleaning',
    priority: 'medium',
    dueDate: '2024-12-27',
    recurrence: { type: 'weekly', interval: 1, daysOfWeek: [3], endDate: null },
    completedDates: [],
    createdAt: '2024-12-01T00:00:00.000Z',
  },
  {
    id: 'c7',
    title: 'Update inventory spreadsheet',
    description: 'Log all supply levels',
    assigneeId: 'tm3',
    category: 'admin',
    priority: 'low',
    dueDate: '2024-12-31',
    recurrence: { type: 'none', interval: 1, daysOfWeek: [], endDate: null },
    completedDates: [],
    createdAt: '2024-12-01T00:00:00.000Z',
  },
  {
    id: 'c8',
    title: 'Clean coffee machine',
    description: 'Run cleaning cycle and descale',
    assigneeId: 'tm4',
    category: 'cleaning',
    priority: 'medium',
    dueDate: '2024-12-28',
    recurrence: { type: 'weekly', interval: 2, daysOfWeek: [6], endDate: null },
    completedDates: [],
    createdAt: '2024-12-01T00:00:00.000Z',
  },
]
